// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentFormController from "./comment_form_controller"
application.register("comment-form", CommentFormController)

import CommentsStatusController from "./comments_status_controller"
application.register("comments-status", CommentsStatusController)

import CopyLinkController from "./copy_link_controller"
application.register("copy-link", CopyLinkController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FormUnsaveCheckerController from "./form_unsave_checker_controller"
application.register("form-unsave-checker", FormUnsaveCheckerController)

import ImageFieldController from "./image_field_controller"
application.register("image-field", ImageFieldController)

import MarkdownFieldController from "./markdown_field_controller"
application.register("markdown-field", MarkdownFieldController)

import PostEditorController from "./post_editor_controller"
application.register("post-editor", PostEditorController)

import RecaptchaController from "./recaptcha_controller"
application.register("recaptcha", RecaptchaController)

import ScrollPaginationController from "./scroll_pagination_controller"
application.register("scroll-pagination", ScrollPaginationController)

import SnackbarController from "./snackbar_controller"
application.register("snackbar", SnackbarController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
