version: '3.4'

services:
  test:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    cap_add:
      - SYS_ADMIN
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
