version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - geeknote-sync:/app:nocopy
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  build-js:
    build:
      context: .
      target: base
    command: npm run build:js -- --watch
    tty: true
    volumes:
      - geeknote-sync:/app:nocopy
  build-css:
    build:
      context: .
      target: base
    command: npm run build:css -- --watch
    volumes:
      - geeknote-sync:/app:nocopy
  worker:
    build:
      context: .
      target: base
    command: bundle exec sidekiq
    volumes:
      - geeknote-sync:/app:nocopy
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:5

volumes:
  geeknote-sync:
    external: true
