version: '3.4'

services:
  ci:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - meilisearch
    cap_add:
      - SYS_ADMIN
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
  meilisearch:
    image: getmeili/meilisearch:v1.0
    environment:
      MEILI_NO_ANALYTICS: true
