version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - meilisearch
    cap_add:
      - SYS_ADMIN
  build-js:
    build:
      context: .
      target: base
    command: npm run build:js -- --watch
    tty: true
    volumes:
      - .:/rails
  build-css:
    build:
      context: .
      target: base
    command: npm run build:css -- --watch
    volumes:
      - .:/rails
  worker:
    build:
      context: .
      target: base
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - postgres
      - redis
    cap_add:
      - SYS_ADMIN
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
  meilisearch:
    image: getmeili/meilisearch:v1.0
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meili-data:/meili_data

volumes:
  meili-data:
