# fly.toml file generated for geeknote-worker on 2022-01-30T20:23:42+08:00

app = "geeknote-worker"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  cmd = ["bundle", "exec", "sidekiq"]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "bin/rails db:migrate"
