version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/rails:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      MEILISEARCH_URL: http://meilisearch:7700

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meili-data:/meili_data

volumes:
  postgres-data:
  meili-data:
