# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: geeknote_development
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: geeknote_development_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: geeknote_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: geeknote_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: geeknote_production
  cache:
    <<: *default
    url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    database: geeknote_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    database: geeknote_production_cable
    migrations_paths: db/cable_migrate
